### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by Laksam2** [Pymmdrza/Convertor_PrivateKey#1]
Can you please write a script to delete the empty key after checking? If there's an interruption, the process will start all over again, checking already checked keys. but if empty keys can be deleted after checking, it should solve the problem.

**Comment by Pymmdrza** [comment]
> Can you please write a script to delete the empty key after checking? If there's an interruption, the process will start all over again, checking already checked keys. but if empty keys can be deleted after checking, it should solve the problem.

what???
