### ISSUE TITLE
Bip38

### ISSUE THREAD

**Issue by Reyhidayat** [Pymmdrza/Convertor_PrivateKey#2]
hi sir, i am very impressed with your hard work so far, but from everything i have seen and followed, i am still stuck with the problem of solving the BIP38 code, do you have a solution for that?

**Comment by Pymmdrza** [comment]
> 

example ? more detail's about question

**Comment by Reyhidayat** [comment]
For example, when I want to enter the private key into my wallet, they ask me for the BIP38 code, but I don't have the code.

**Comment by Pymmdrza** [comment]
> 

can use hdwallet
